"""
Python Generators
In Python, a generator is a function that returns an iterator that produces a sequence of values 
when iterated over.

Generators are useful when we want to produce a large sequence of values, but we don't want to 
store all of them in memory at once.

Syntax of Generator Expression: (expression for item in iterable)

"""
# Define a simple generator function
def count_up_to(max_value):
    count = 1
    while count <= max_value:
        yield count  # Yield the current count value
        count += 1

# Create a generator object
counter = count_up_to(5)
print(counter, type(counter))
# Iterate over the generator
for num in counter:
    print(num)

print("==============================")
"""
Fibanaaci series with Generator:
"""
def fibonacci():
    a, b = 0, 1
    while True:
        yield a  # Yield the current Fibonacci number
        a, b = b, a + b  # Update the next numbers in the sequence

# Create the Fibonacci generator
fib_gen = fibonacci()

# Get the first 10 Fibonacci numbers
for _ in range(10):
    print(next(fib_gen))


"""
In Python, list comprehensions and generators are related, but they are not the same thing. 
Here's the distinction:

1. List Comprehension:
---------------------
A list comprehension creates and returns a list. The entire list is computed and stored in 
memory at once, which means it's not memory-efficient for large datasets.

Example:
--------
squares = [x**2 for x in range(5)]
print(squares)

Output:
-------
[0, 1, 4, 9, 16]
Here, squares is a list containing all the squared values generated by the comprehension.
All values are generated at once and stored in memory.

2. Generator Expression:
-----------------------
A generator expression is similar in syntax to a list comprehension but uses parentheses ()
instead of square brackets []. It returns a generator object, which produces items lazily, 
one at a time, and doesn't store the entire result in memory.

Example:
squares_gen = (x**2 for x in range(5))
print(squares_gen)  # This will print a generator object, not the values

for val in squares_gen:
    print(val)

Output:
-------
<generator object <genexpr> at 0x...>  # This is the generator object
0
1
4
9
16
=======================================================
The generator expression computes values on demand using the yield mechanism internally. 
It is more memory-efficient, especially for large datasets, because it only computes and yields 
one item at a time.

Key Differences:
List Comprehension:

Returns a list.
Values are generated all at once and stored in memory.
Syntax: [expression for item in iterable].
Generator Expression:

Returns a generator object.
Values are generated lazily (one at a time, on-demand).
Syntax: (expression for item in iterable).

Example Comparison:
------------------
List comprehension (holds all values in memory):
squares = [x**2 for x in range(10**6)]  # Creates a large list in memory

Generator expression (generates values one by one):
--------------------------------------------------
squares_gen = (x**2 for x in range(10**6))  # Only generates values when needed, saving memory

Conclusion: A list comprehension is not a generator. It creates a list and stores all values at once.
However, a generator expression behaves like a generator and produces values lazily, which makes it 
more memory-efficient.
"""